// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameArticleSearchIndex = "article_search_index"

// ArticleSearchIndex mapped from table <article_search_index>
type ArticleSearchIndex struct {
	ID           int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TicketID     int64   `gorm:"column:ticket_id;not null" json:"ticket_id"`
	ArticleID    int64   `gorm:"column:article_id;not null" json:"article_id"`
	ArticleKey   string  `gorm:"column:article_key;not null" json:"article_key"`
	ArticleValue *string `gorm:"column:article_value" json:"article_value"`
}

// TableName ArticleSearchIndex's table name
func (*ArticleSearchIndex) TableName() string {
	return TableNameArticleSearchIndex
}
