// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameArticle = "article"

// Article mapped from table <article>
type Article struct {
	ID                      int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TicketID                int64     `gorm:"column:ticket_id;not null" json:"ticket_id"`
	ArticleSenderTypeID     int32     `gorm:"column:article_sender_type_id;not null" json:"article_sender_type_id"`
	CommunicationChannelID  int64     `gorm:"column:communication_channel_id;not null" json:"communication_channel_id"`
	IsVisibleForCustomer    int32     `gorm:"column:is_visible_for_customer;not null" json:"is_visible_for_customer"`
	SearchIndexNeedsRebuild int32     `gorm:"column:search_index_needs_rebuild;not null;default:1" json:"search_index_needs_rebuild"`
	InsertFingerprint       *string   `gorm:"column:insert_fingerprint" json:"insert_fingerprint"`
	CreateTime              time.Time `gorm:"column:create_time;not null" json:"create_time"`
	CreateBy                int32     `gorm:"column:create_by;not null" json:"create_by"`
	ChangeTime              time.Time `gorm:"column:change_time;not null" json:"change_time"`
	ChangeBy                int32     `gorm:"column:change_by;not null" json:"change_by"`
}

// TableName Article's table name
func (*Article) TableName() string {
	return TableNameArticle
}
