// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameArticleFlag = "article_flag"

// ArticleFlag mapped from table <article_flag>
type ArticleFlag struct {
	ArticleID    int64     `gorm:"column:article_id;not null" json:"article_id"`
	ArticleKey   string    `gorm:"column:article_key;not null" json:"article_key"`
	ArticleValue *string   `gorm:"column:article_value" json:"article_value"`
	CreateTime   time.Time `gorm:"column:create_time;not null" json:"create_time"`
	CreateBy     int32     `gorm:"column:create_by;not null" json:"create_by"`
}

// TableName ArticleFlag's table name
func (*ArticleFlag) TableName() string {
	return TableNameArticleFlag
}
