// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAutoResponse = "auto_response"

// AutoResponse mapped from table <auto_response>
type AutoResponse struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name            string    `gorm:"column:name;not null" json:"name"`
	Text0           *string   `gorm:"column:text0" json:"text0"`
	Text1           *string   `gorm:"column:text1" json:"text1"`
	TypeID          int32     `gorm:"column:type_id;not null" json:"type_id"`
	SystemAddressID int32     `gorm:"column:system_address_id;not null" json:"system_address_id"`
	ContentType     *string   `gorm:"column:content_type" json:"content_type"`
	Comments        *string   `gorm:"column:comments" json:"comments"`
	ValidID         int32     `gorm:"column:valid_id;not null" json:"valid_id"`
	CreateTime      time.Time `gorm:"column:create_time;not null" json:"create_time"`
	CreateBy        int32     `gorm:"column:create_by;not null" json:"create_by"`
	ChangeTime      time.Time `gorm:"column:change_time;not null" json:"change_time"`
	ChangeBy        int32     `gorm:"column:change_by;not null" json:"change_by"`
}

// TableName AutoResponse's table name
func (*AutoResponse) TableName() string {
	return TableNameAutoResponse
}
