// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCommunicationChannel = "communication_channel"

// CommunicationChannel mapped from table <communication_channel>
type CommunicationChannel struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Module      string    `gorm:"column:module;not null" json:"module"`
	PackageName string    `gorm:"column:package_name;not null" json:"package_name"`
	ChannelData []byte    `gorm:"column:channel_data;not null" json:"channel_data"`
	ValidID     int32     `gorm:"column:valid_id;not null" json:"valid_id"`
	CreateTime  time.Time `gorm:"column:create_time;not null" json:"create_time"`
	CreateBy    int32     `gorm:"column:create_by;not null" json:"create_by"`
	ChangeTime  time.Time `gorm:"column:change_time;not null" json:"change_time"`
	ChangeBy    int32     `gorm:"column:change_by;not null" json:"change_by"`
}

// TableName CommunicationChannel's table name
func (*CommunicationChannel) TableName() string {
	return TableNameCommunicationChannel
}
