// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCommunicationLog = "communication_log"

// CommunicationLog mapped from table <communication_log>
type CommunicationLog struct {
	ID                int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	InsertFingerprint *string    `gorm:"column:insert_fingerprint" json:"insert_fingerprint"`
	Transport         string     `gorm:"column:transport;not null" json:"transport"`
	Direction         string     `gorm:"column:direction;not null" json:"direction"`
	Status            string     `gorm:"column:status;not null" json:"status"`
	AccountType       *string    `gorm:"column:account_type" json:"account_type"`
	AccountID         *string    `gorm:"column:account_id" json:"account_id"`
	StartTime         time.Time  `gorm:"column:start_time;not null" json:"start_time"`
	EndTime           *time.Time `gorm:"column:end_time" json:"end_time"`
}

// TableName CommunicationLog's table name
func (*CommunicationLog) TableName() string {
	return TableNameCommunicationLog
}
