// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFaqCategory = "faq_category"

// FaqCategory mapped from table <faq_category>
type FaqCategory struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ParentID  int32     `gorm:"column:parent_id;not null" json:"parent_id"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Comments  *string   `gorm:"column:comments" json:"comments"`
	ValidID   int32     `gorm:"column:valid_id;not null" json:"valid_id"`
	Created   time.Time `gorm:"column:created;not null" json:"created"`
	CreatedBy int32     `gorm:"column:created_by;not null" json:"created_by"`
	Changed   time.Time `gorm:"column:changed;not null" json:"changed"`
	ChangedBy int32     `gorm:"column:changed_by;not null" json:"changed_by"`
}

// TableName FaqCategory's table name
func (*FaqCategory) TableName() string {
	return TableNameFaqCategory
}
