// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSmimeSignerCertRelation = "smime_signer_cert_relations"

// SmimeSignerCertRelation mapped from table <smime_signer_cert_relations>
type SmimeSignerCertRelation struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CertHash        string    `gorm:"column:cert_hash;not null" json:"cert_hash"`
	CertFingerprint string    `gorm:"column:cert_fingerprint;not null" json:"cert_fingerprint"`
	CaHash          string    `gorm:"column:ca_hash;not null" json:"ca_hash"`
	CaFingerprint   string    `gorm:"column:ca_fingerprint;not null" json:"ca_fingerprint"`
	CreateTime      time.Time `gorm:"column:create_time;not null" json:"create_time"`
	CreateBy        int32     `gorm:"column:create_by;not null" json:"create_by"`
	ChangeTime      time.Time `gorm:"column:change_time;not null" json:"change_time"`
	ChangeBy        int32     `gorm:"column:change_by;not null" json:"change_by"`
}

// TableName SmimeSignerCertRelation's table name
func (*SmimeSignerCertRelation) TableName() string {
	return TableNameSmimeSignerCertRelation
}
