// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWebUploadCache = "web_upload_cache"

// WebUploadCache mapped from table <web_upload_cache>
type WebUploadCache struct {
	FormID         *string `gorm:"column:form_id" json:"form_id"`
	Filename       *string `gorm:"column:filename" json:"filename"`
	ContentID      *string `gorm:"column:content_id" json:"content_id"`
	ContentSize    *string `gorm:"column:content_size" json:"content_size"`
	ContentType    *string `gorm:"column:content_type" json:"content_type"`
	Disposition    *string `gorm:"column:disposition" json:"disposition"`
	Content        []byte  `gorm:"column:content;not null" json:"content"`
	CreateTimeUnix int64   `gorm:"column:create_time_unix;not null" json:"create_time_unix"`
}

// TableName WebUploadCache's table name
func (*WebUploadCache) TableName() string {
	return TableNameWebUploadCache
}
