// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"tg_bot/internal/database/model"
)

func newRoleUser(db *gorm.DB, opts ...gen.DOOption) roleUser {
	_roleUser := roleUser{}

	_roleUser.roleUserDo.UseDB(db, opts...)
	_roleUser.roleUserDo.UseModel(&model.RoleUser{})

	tableName := _roleUser.roleUserDo.TableName()
	_roleUser.ALL = field.NewAsterisk(tableName)
	_roleUser.UserID = field.NewInt32(tableName, "user_id")
	_roleUser.RoleID = field.NewInt32(tableName, "role_id")
	_roleUser.CreateTime = field.NewTime(tableName, "create_time")
	_roleUser.CreateBy = field.NewInt32(tableName, "create_by")
	_roleUser.ChangeTime = field.NewTime(tableName, "change_time")
	_roleUser.ChangeBy = field.NewInt32(tableName, "change_by")

	_roleUser.fillFieldMap()

	return _roleUser
}

type roleUser struct {
	roleUserDo

	ALL        field.Asterisk
	UserID     field.Int32
	RoleID     field.Int32
	CreateTime field.Time
	CreateBy   field.Int32
	ChangeTime field.Time
	ChangeBy   field.Int32

	fieldMap map[string]field.Expr
}

func (r roleUser) Table(newTableName string) *roleUser {
	r.roleUserDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r roleUser) As(alias string) *roleUser {
	r.roleUserDo.DO = *(r.roleUserDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *roleUser) updateTableName(table string) *roleUser {
	r.ALL = field.NewAsterisk(table)
	r.UserID = field.NewInt32(table, "user_id")
	r.RoleID = field.NewInt32(table, "role_id")
	r.CreateTime = field.NewTime(table, "create_time")
	r.CreateBy = field.NewInt32(table, "create_by")
	r.ChangeTime = field.NewTime(table, "change_time")
	r.ChangeBy = field.NewInt32(table, "change_by")

	r.fillFieldMap()

	return r
}

func (r *roleUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *roleUser) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 6)
	r.fieldMap["user_id"] = r.UserID
	r.fieldMap["role_id"] = r.RoleID
	r.fieldMap["create_time"] = r.CreateTime
	r.fieldMap["create_by"] = r.CreateBy
	r.fieldMap["change_time"] = r.ChangeTime
	r.fieldMap["change_by"] = r.ChangeBy
}

func (r roleUser) clone(db *gorm.DB) roleUser {
	r.roleUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r roleUser) replaceDB(db *gorm.DB) roleUser {
	r.roleUserDo.ReplaceDB(db)
	return r
}

type roleUserDo struct{ gen.DO }

type IRoleUserDo interface {
	gen.SubQuery
	Debug() IRoleUserDo
	WithContext(ctx context.Context) IRoleUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRoleUserDo
	WriteDB() IRoleUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRoleUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRoleUserDo
	Not(conds ...gen.Condition) IRoleUserDo
	Or(conds ...gen.Condition) IRoleUserDo
	Select(conds ...field.Expr) IRoleUserDo
	Where(conds ...gen.Condition) IRoleUserDo
	Order(conds ...field.Expr) IRoleUserDo
	Distinct(cols ...field.Expr) IRoleUserDo
	Omit(cols ...field.Expr) IRoleUserDo
	Join(table schema.Tabler, on ...field.Expr) IRoleUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRoleUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRoleUserDo
	Group(cols ...field.Expr) IRoleUserDo
	Having(conds ...gen.Condition) IRoleUserDo
	Limit(limit int) IRoleUserDo
	Offset(offset int) IRoleUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRoleUserDo
	Unscoped() IRoleUserDo
	Create(values ...*model.RoleUser) error
	CreateInBatches(values []*model.RoleUser, batchSize int) error
	Save(values ...*model.RoleUser) error
	First() (*model.RoleUser, error)
	Take() (*model.RoleUser, error)
	Last() (*model.RoleUser, error)
	Find() ([]*model.RoleUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoleUser, err error)
	FindInBatches(result *[]*model.RoleUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RoleUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRoleUserDo
	Assign(attrs ...field.AssignExpr) IRoleUserDo
	Joins(fields ...field.RelationField) IRoleUserDo
	Preload(fields ...field.RelationField) IRoleUserDo
	FirstOrInit() (*model.RoleUser, error)
	FirstOrCreate() (*model.RoleUser, error)
	FindByPage(offset int, limit int) (result []*model.RoleUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRoleUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r roleUserDo) Debug() IRoleUserDo {
	return r.withDO(r.DO.Debug())
}

func (r roleUserDo) WithContext(ctx context.Context) IRoleUserDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r roleUserDo) ReadDB() IRoleUserDo {
	return r.Clauses(dbresolver.Read)
}

func (r roleUserDo) WriteDB() IRoleUserDo {
	return r.Clauses(dbresolver.Write)
}

func (r roleUserDo) Session(config *gorm.Session) IRoleUserDo {
	return r.withDO(r.DO.Session(config))
}

func (r roleUserDo) Clauses(conds ...clause.Expression) IRoleUserDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r roleUserDo) Returning(value interface{}, columns ...string) IRoleUserDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r roleUserDo) Not(conds ...gen.Condition) IRoleUserDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r roleUserDo) Or(conds ...gen.Condition) IRoleUserDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r roleUserDo) Select(conds ...field.Expr) IRoleUserDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r roleUserDo) Where(conds ...gen.Condition) IRoleUserDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r roleUserDo) Order(conds ...field.Expr) IRoleUserDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r roleUserDo) Distinct(cols ...field.Expr) IRoleUserDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r roleUserDo) Omit(cols ...field.Expr) IRoleUserDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r roleUserDo) Join(table schema.Tabler, on ...field.Expr) IRoleUserDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r roleUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRoleUserDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r roleUserDo) RightJoin(table schema.Tabler, on ...field.Expr) IRoleUserDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r roleUserDo) Group(cols ...field.Expr) IRoleUserDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r roleUserDo) Having(conds ...gen.Condition) IRoleUserDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r roleUserDo) Limit(limit int) IRoleUserDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r roleUserDo) Offset(offset int) IRoleUserDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r roleUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRoleUserDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r roleUserDo) Unscoped() IRoleUserDo {
	return r.withDO(r.DO.Unscoped())
}

func (r roleUserDo) Create(values ...*model.RoleUser) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r roleUserDo) CreateInBatches(values []*model.RoleUser, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r roleUserDo) Save(values ...*model.RoleUser) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r roleUserDo) First() (*model.RoleUser, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleUser), nil
	}
}

func (r roleUserDo) Take() (*model.RoleUser, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleUser), nil
	}
}

func (r roleUserDo) Last() (*model.RoleUser, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleUser), nil
	}
}

func (r roleUserDo) Find() ([]*model.RoleUser, error) {
	result, err := r.DO.Find()
	return result.([]*model.RoleUser), err
}

func (r roleUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoleUser, err error) {
	buf := make([]*model.RoleUser, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r roleUserDo) FindInBatches(result *[]*model.RoleUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r roleUserDo) Attrs(attrs ...field.AssignExpr) IRoleUserDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r roleUserDo) Assign(attrs ...field.AssignExpr) IRoleUserDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r roleUserDo) Joins(fields ...field.RelationField) IRoleUserDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r roleUserDo) Preload(fields ...field.RelationField) IRoleUserDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r roleUserDo) FirstOrInit() (*model.RoleUser, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleUser), nil
	}
}

func (r roleUserDo) FirstOrCreate() (*model.RoleUser, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleUser), nil
	}
}

func (r roleUserDo) FindByPage(offset int, limit int) (result []*model.RoleUser, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r roleUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r roleUserDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r roleUserDo) Delete(models ...*model.RoleUser) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *roleUserDo) withDO(do gen.Dao) *roleUserDo {
	r.DO = *do.(*gen.DO)
	return r
}
