name: Go Test

on:
  push:
    branches:
      - main
      - '*'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          go.mod
          go.sum
        key: ${{ runner.os }}-go-${{ hashFiles('**/*.mod', '**/*.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - run: go version
    - run: go get github.com/go-telegram-bot-api/telegram-bot-api/v5
    - name: Test
      run: go test -v ./...
  coverage:
    name: Coverage
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'

    - name: Check out code
      uses: actions/checkout@v4

    - name: Test with Coverage
      run: go test -v -coverprofile=coverage.out ./...

    - name: Generate Coverage Report
      run: go tool cover -html=coverage.out -o coverage.html

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.html
        retention-days: 5
  docker:
    name: Docker push
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag
        id: version
        run: echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/v}"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/Dockerfile
          push: true
          tags: ilyaksyonov/gotgbot:latest
          # tags: ilyaksyonov/gotgbot:${{ steps.version.outputs.VERSION }}