name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test
    runs-on: self-hosted
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.3'
    - name: Check out code
      uses: actions/checkout@v2
    - name: Test
      run: go test -v ./...
  coverage:
    name: Coverage
    runs-on: self-hosted
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.3'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test with Coverage
      run: go test -v -coverprofile=coverage.out ./...

    - name: Generate Coverage Report
      run: go tool cover -html=coverage.out -o coverage.html

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.html
        retention-days: 5
